workflows:
  android:
    name: Android Release Build
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Clean Gradle Cache
        script: |
          ./gradlew cleanBuildCache
      - name: Build Android APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/**/*.apk
    publishing:
      scripts:
        - name: Publish APK
          script: |
            # Publish your APK here
            echo "Publish the APK to your store"
