workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: 18
      java: 11
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=${{ANDROID_SDK_ROOT}}" > "${{CM_BUILD_DIR}}/android/local.properties"
      - name: Build Android release
        script: |
          chmod +x android/gradlew
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
