workflows:
  android:
    name: Build Android Release APK
    max_build_duration: 60
    environment:
      node: 16.0.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Clean Gradle Cache
        script: |
          cd android && ./gradlew cleanBuildCache || true
      - name: Build Android APK
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
      - build/app/outputs/**/*.apk
